name: Docker

on:
  workflow_call:
    

jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Download main compilado
      uses: actions/download-artifact@v3
      with:
        name: programa

    - name: setup Docker Buil
      uses: docker/setup-buildx-action@v2.0.0

    - name: Docker Login
      # You may pin to the exact commit or the version.
      # uses: docker/login-action@49ed152c8eca782a232dede0303416e8f356c37b
      uses: docker/login-action@v2.0.0
      with:
        # Username used to log against the Docker registry
        username: htschannerl
        # Password or personal access token used to log against the Docker registry
        password: ${{ secrets.PASSWORD_DOCKER_HUB }}

    - name: Build and push Docker images
      # You may pin to the exact commit or the version.
      # uses: docker/build-push-action@e551b19e49efd4e98792db7592c17c09b89db8d8
      uses: docker/build-push-action@v3.0.0
      with:
        # Build's context is the set of files located in the specified PATH or URL
        context: .
        # Path to the Dockerfile
        file: ./Dockerfile
        # Push is a shorthand for --output=type=registry
        push: true
        # List of tags
        tags: htschannerl/go_ci:${{github.ref_name}}
